name: Convert Notebooks to LaTeX
on:
  push

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install jupyter and nbconvert
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert

    - name: Install pandoc
      run: |
        sudo apt-get install pandoc

    - name: Install LateX
      run: |
        sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic

    - name: Create artifact directory
      run: |
        mkdir -p artifacts/latex
        rm -rf artifacts/latex/*  # Clean any existing files

    - name: Create file list
      id: files_list
      run: |
        # Collect all .ipynb files (non-hidden directories and files)
        files=$(find . -name "*.ipynb" -not -path "*/\.*" -not -path "*/artifacts/*")
        
        # Format into a space-separated string with quoted filenames
        formatted_files=$(printf '"%s" ' $files)
        
        # Set the output variable
        echo "files=$formatted_files" >> $GITHUB_OUTPUT
    
        # Optional: echo for debugging
        echo $formatted_files

    - name: Convert notebooks to LaTeX
      run: |
        jupyter nbconvert --to latex --output="artifacts/latex" ${{ steps.files_list.outputs.files }}


    - name: GitHub Pages action
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: latex-files         # The branch the action should deploy to.
        folder: artifacts/latex     # The folder the action should deploy.