name: Convert Notebooks to RMarkdown
on:
  push:
  #  paths:
  #    - '**.ipynb'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install jupyter, jupytext, fire, loguru
      run: |
        python -m pip install --upgrade pip
        pip install nbformat jupytext fire loguru

    - name: Create artifact directory
      run: |
        mkdir -p artifacts/rmd
        rm -rf artifacts/rmd/*  # Clean any existing files

    - name: Render all notebooks
      run: |
        python .github/scripts/render.py render config_rmd.json .

    - name: Convert notebooks to RMarkdown
      run: |
        # Find all notebooks in the repository
        NOTEBOOKS=$(find . -name "*.ipynb" -not -path "*/\.*" -not -path "*/artifacts/*")
        
        # Convert each notebook
        for nb in $NOTEBOOKS; do
          echo "Converting $nb to Rmd..."
          # Get the base name without path and extension
          base_name=$(basename "$nb" .ipynb)
          
          # Convert to Rmd in the artifacts directory
          jupytext --to rmarkdown "$nb" --output "artifacts/rmd/${base_name}.Rmd"
        done
    
    - name: Copy data folder
      run: |
        cp -r data artifacts/rmd
    
    #- name: Upload conversion results
    #  if: always()
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: rmd-files
    #    path: artifacts/rmd/
    #    retention-days: 1

    - name: GitHub Pages action
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: rmd-files         # The branch the action should deploy to.
        folder: artifacts/rmd     # The folder the action should deploy.
